import React from 'react';
import ScrollerLoader from '../Common/ScrollerLoader';

export default function Test() {
  return (
    <div>
      <ScrollerLoader
        actionWhenScrolling={() => {
          console.log('scrolled b');
        }}
        actionWhenBottom={() => console.log('bottom')}
        styles={{ width: '300px', height: '400px' }}
      >
        <div>
          <ul>
            <li>dffsdffddfsfdshadjshjdsahj</li>
            <li>dffsdffddfsfdssdjhhjdshjsd</li>
            <li>dffsdffddfsfdssdhjdshjhjds</li>
            <li>dffsdffddfsfdsdjshdjshjds</li>
            <li>dffsdffddfsfdsjhdshjdshj</li>
            <li>dffsdffddfsfdssdhj</li>
            <li>dffsdffddfsfdsshjdshj</li>
            <li>dffsdffddfsfdsds</li>
            <li>dffsdffddfsfdsshjds</li>
            <li>dffsdffddfsfdshjdshj</li>
            <li>dffsdffddfsfdsdhjddshjhdjs</li>
            <li>dffsdffddfsfdshjdshdhsdjh</li>
            <li>dffsdffddfsfdsdjh</li>
            <li>dffsdffddfsfdsdhshds</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdshh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfdsh</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
            <li>dffsdffddfsfds</li>
          </ul>
        </div>
      </ScrollerLoader>
    </div>
  );
}
