version: '3'

services:
  chat:
    build: ./chat
    expose:
      - ${CHAT_PORT}
    domainname: local
    environment:
      CHAT_HOST: ${CHAT_HOST}
      CHAT_PORT: ${CHAT_PORT}
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    volumes:
      - ./chat/:/srv/app/grampy-chat
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/:/srv/app/grampy-server
    command: npm run server
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/grampy-client/src
      - ./client/public:/srv/app/grampy-client/public
    links:
      - server
    command: npm run start
