version: '3'

services:
  elasticsearch:
    container_name: 'elasticsearch'
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - network.host=0.0.0.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - '9200:9200'
      - '9300:9300'

  chat:
    build: ./chat
    expose:
      - ${CHAT_PORT}
    domainname: local
    environment:
      CHAT_HOST: ${CHAT_HOST}
      CHAT_PORT: ${CHAT_PORT}
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    volumes:
      - ./chat/:/srv/app/grampy-chat
    depends_on:
      - elasticsearch
  image:
    build: ./image
    environment:
      IMAGE_HOST: ${IMAGE_HOST}
      IMAGE_PORT: ${IMAGE_PORT}
    ports:
      - '2222:2222'
    volumes:
      - ./image/temp:/app/temp
    networks:
      - image_net

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/:/srv/app/grampy-server
    command: npm run server
    networks:
      - image_net
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/grampy-client/src
      - ./client/public:/srv/app/grampy-client/public
    links:
      - server
    command: npm run start
networks:
  image_net:
    driver: bridge
